package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Comment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated
     */
    List<Comment> selectAll();

    Comment selectByComID(@Param("comID") int comID);

    List<Comment> selectByUID(@Param("uid") int uid);

    List<Comment> selectByUIDAndType(@Param("uid")  int uid, @Param("comtype") int comtype);

    List<Comment> selectByToIDAndType(@Param("toid")  int toid, @Param("comtype") int comtype);

    List<Comment> selectByUIDAndTypeAndToID(@Param("uid") int uid,
                                            @Param("comtype")int comtype,
                                            @Param("toid")int toid);

    int deleteByComID(@Param("comID") int comID);
}