package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Like;
import java.util.List;

public interface LikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    int insert(Like record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like
     *
     * @mbggenerated
     */
    List<Like> selectAll();
}