package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Login;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     * 注册接口
     * @mbggenerated
     */
    int insert(Login record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    List<Login> selectAll();

    /**
     * 登陆账号校验
     * @param loginID 用户名id
     * @param passWord 密码
     * @return true 校验通过，false 检验失败
     */
    boolean loginCheck(int loginID , String passWord);


    /**
     *  用户登陆生命周期查询
     * @param LoginID 登陆的用户id
     * @return 生命周期：20天，比较当前时间和上次登陆时间的差值；若小于20天，则说明登陆信息有效
     *              否则，需要重新登陆。
     */

    boolean liveTimeCheck(int LoginID);


}