package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Palcircle;
import java.util.List;

public interface PalcircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table palcircle
     *
     * @mbggenerated
     */
    int insert(Palcircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table palcircle
     *
     * @mbggenerated
     */
    List<Palcircle> selectAll();
}