package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Series;
import com.lemonbily.springboot.entity.Video;

import java.util.List;

public interface SeriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    int insert(Series record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table series
     *
     * @mbggenerated
     */
    List<Series> selectAll();

    Series selectBySID(int sid);

    int update(Series series);

    int deleteBySID(int sid);
}