package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Account;
import com.lemonbily.springboot.entity.Video;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    List<Video> selectAll();

    Video selectByVID(@Param("vid") int vid);

    List<Video> selectBySID(@Param("sid") int sid);

    int update(Video video);

    int updateAddPlay(@Param("vid") int vid);

    int deleteByVID(@Param("vid") int vid);
}