package com.lemonbily.springboot.mapper;

import com.lemonbily.springboot.entity.Account;
import com.lemonbily.springboot.entity.Video;
import java.util.List;

public interface VideoMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    List<Video> selectAll();

    Video selectByVID(int vid);

    List<Video> selectBySID(int sid);

    int update(Video video);

    int deleteByVID(int vid);
}