package com.lemonbily.springboot.entity;

import java.io.Serializable;

public class Video implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VID
     *
     * @mbggenerated
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.SID
     *
     * @mbggenerated
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VName
     *
     * @mbggenerated
     */
    private String vname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VDescribe
     *
     * @mbggenerated
     */
    private String vdescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VPath
     *
     * @mbggenerated
     */
    private String vpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VPicture
     *
     * @mbggenerated
     */
    private String vpicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.VPlayNum
     *
     * @mbggenerated
     */
    private Integer vplaynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VID
     *
     * @return the value of video.VID
     *
     * @mbggenerated
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VID
     *
     * @param vid the value for video.VID
     *
     * @mbggenerated
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.SID
     *
     * @return the value of video.SID
     *
     * @mbggenerated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.SID
     *
     * @param sid the value for video.SID
     *
     * @mbggenerated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VName
     *
     * @return the value of video.VName
     *
     * @mbggenerated
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VName
     *
     * @param vname the value for video.VName
     *
     * @mbggenerated
     */
    public void setVname(String vname) {
        this.vname = vname == null ? null : vname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VDescribe
     *
     * @return the value of video.VDescribe
     *
     * @mbggenerated
     */
    public String getVdescribe() {
        return vdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VDescribe
     *
     * @param vdescribe the value for video.VDescribe
     *
     * @mbggenerated
     */
    public void setVdescribe(String vdescribe) {
        this.vdescribe = vdescribe == null ? null : vdescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VPath
     *
     * @return the value of video.VPath
     *
     * @mbggenerated
     */
    public String getVpath() {
        return vpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VPath
     *
     * @param vpath the value for video.VPath
     *
     * @mbggenerated
     */
    public void setVpath(String vpath) {
        this.vpath = vpath == null ? null : vpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VPicture
     *
     * @return the value of video.VPicture
     *
     * @mbggenerated
     */
    public String getVpicture() {
        return vpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VPicture
     *
     * @param vpicture the value for video.VPicture
     *
     * @mbggenerated
     */
    public void setVpicture(String vpicture) {
        this.vpicture = vpicture == null ? null : vpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.VPlayNum
     *
     * @return the value of video.VPlayNum
     *
     * @mbggenerated
     */
    public Integer getVplaynum() {
        return vplaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.VPlayNum
     *
     * @param vplaynum the value for video.VPlayNum
     *
     * @mbggenerated
     */
    public void setVplaynum(Integer vplaynum) {
        this.vplaynum = vplaynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vid=").append(vid);
        sb.append(", sid=").append(sid);
        sb.append(", vname=").append(vname);
        sb.append(", vdescribe=").append(vdescribe);
        sb.append(", vpath=").append(vpath);
        sb.append(", vpicture=").append(vpicture);
        sb.append(", vplaynum=").append(vplaynum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}